### ISSUE TITLE
正常動作できません

### ISSUE THREAD

**Issue by abeq** [junishitsuka/flasher-desktop#13]
"Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead." というエラーが表示されますが、修正すべき 'findDOMNode' を使用している箇所が見つけられません。
ご確認いただけますでしょうか？

**Comment by junishitsuka** [comment]
https://github.com/gaearon/redux-devtools/issues/190

redux-devtoolsが原因のようです.
Warningだったのでそこまで気にしていませんでした.

**Comment by junishitsuka** [comment]
このコミットをrevertすればエラーが消えると思います.

https://github.com/junishitsuka/flasher-desktop/commit/aa394635321d70886f59913e0b07a4123ce3e7fe

**Comment by abeq** [comment]
ご教示ありがとうございました。
エラーが消え、正常動作しました。
